/*
 / _____)             _              | |
( (____  _____ ____ _| |_ _____  ____| |__
 \____ \| ___ |    (_   _) ___ |/ ___)  _ \
 _____) ) ____| | | || |_| ____( (___| | | |
(______/|_____)_|_|_| \__)_____)\____)_| |_|
    (C)2015 Semtech

Description: End device commissioning parameters

License: Revised BSD License, see LICENSE.TXT file include in the project

Maintainer: Miguel Luis and Gregory Cristian
*/
#ifndef __LORA_COMMISSIONING_H__
#define __LORA_COMMISSIONING_H__

#define LORAMAC_REGION_DEFAULT		LORAMAC_REGION_KR920
/*!
 * When set to 1 the application uses the Over-the-Air activation procedure
 * When set to 0 the application uses the Personalization activation procedure
 */
#define OVER_THE_AIR_ACTIVATION                     1

/*!
 * Indicates if the end-device is to be connected to a private or public network
 */
#define LORAWAN_PUBLIC_NETWORK                      true

/*!
 * IEEE Organizationally Unique Identifier ( OUI ) (big endian)
 * \remark This is unique to a company or organization
 */
#define IEEE_OUI                                    0x00, 0x40, 0x5c

/*!
 * Mote device IEEE EUI (big endian)
 *
 * \remark In this application the value is automatically generated by calling
 *         BoardGetUniqueId function
 */
#if (OVER_THE_AIR_ACTIVATION > 0)
#define LORAWAN_DEVICE_EUI                          { IEEE_OUI, 0x4F, 0x4D, 0x00, 0x00, 0x01 }
#else
#define LORAWAN_DEVICE_EUI                          { IEEE_OUI, 0x4F, 0x4D, 0x00, 0x00, 0x02 }
#endif
/*!
 * Application IEEE EUI (big endian)
 */

#define LORAWAN_APPLICATION_EUI                     { 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x03 }

//#define LORAWAN_APPLICATION_EUI 					{ 0x70, 0xB3, 0xD5, 0x7E, 0xF0, 0x00, 0x57, 0x84 }
/*!
 * AES encryption/decryption cipher application key
 */
// OTB
// #define LORAWAN_APPLICATION_KEY						{0xc0, 0x5c, 0x33, 0xac, 0x2e, 0xb7, 0xcb, 0x08, 0x20, 0x73, 0xb5, 0xe4, 0x67, 0xf8, 0x1f, 0x5d}
#define LORAWAN_APPLICATION_KEY						{0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x05}
/*!
 * Current network ID
 */
#define LORAWAN_NETWORK_ID                          ( uint32_t )0

/*!
 * Device address on the network (big endian)
 *
 * \remark In this application the value is automatically generated using
 *         a pseudo random generator seeded with a value derived from
 *         BoardUniqueId value if LORAWAN_DEVICE_ADDRESS is set to 0
 */
//#define LORAWAN_DEVICE_ADDRESS                      ( uint32_t )0x260118C8
#define LORAWAN_DEVICE_ADDRESS                      ( uint32_t )0x2601268E

/*!
 * AES encryption/decryption cipher network session key
 */
#define LORAWAN_NWKSKEY                             { 0xD0, 0x75, 0xA4, 0x3A, 0x54, 0x38, 0x35, 0xBB, 0x6E, 0x44, 0x8F, 0xC0, 0xB2, 0xF4, 0x53, 0x67 }
													//{ 0x2B, 0x7E, 0x15, 0x16, 0x28, 0xAE, 0xD2, 0xA6, 0xAB, 0xF7, 0x15, 0x88, 0x09, 0xCF, 0x4F, 0x3C }

/*!
 * AES encryption/decryption cipher application session key
 */
#define LORAWAN_APPSKEY                             { 0xD4, 0xC6, 0xFA, 0x02, 0x3B, 0x15, 0xB9, 0x5F, 0xD4, 0xC1, 0xAC, 0x21, 0x77, 0x06, 0x79, 0x40 }
//{ 0x2B, 0x7E, 0x15, 0x16, 0x28, 0xAE, 0xD2, 0xA6, 0xAB, 0xF7, 0x15, 0x88, 0x09, 0xCF, 0x4F, 0x3C }

#endif // __LORA_COMMISSIONING_H__
